version: '3'
services:
  postgres:
    image: "postgres:13"
    container_name: 'java-postgres-feed'
    ports:
      - "5431:5432"
    environment:
      - 'POSTGRES_DB=feed'
      - 'POSTGRES_USER=usr'
      - 'POSTGRES_PASSWORD=pwd'
    volumes:
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    # user/pwd: guest/guest