CREATE SCHEMA IF NOT EXISTS feed;
GRANT ALL PRIVILEGES ON DATABASE feed TO usr;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA feed TO usr;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA feed TO usr;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA feed TO usr;
