server:
  port: ${SERVER_PORT:8084}
  shutdown: graceful

management:
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoint:
    health:
      group:
        readiness:
          include: diskSpace, readinessState
      show-details: "ALWAYS"
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health

spring:
  application:
    name: SpxFeedCbr
  main:
    banner-mode: off
#    allow-bean-definition-overriding: true

  rabbitmq:
    host: ${RABBIT_HOST:10.219.160.21}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:admin}
    password: ${RABBIT_PASSWORD}

    cbr:
      exchange: ${RABBIT_FEED_CBR_EXCHANGE:spx-feed-cbr-currency-exchange}
    rates:
      exchange: ${RABBIT_FEED_CBR_RATES_EXCHANGE:spx-feed-cbr-currency-rate-exchange}
    metal:
      exchange: ${RABBIT_FEED_METAL_EXCHANGE:spx-feed-cbr-metal-rate-exchange}
    ruonia:
      exchange: ${RABBIT_FEED_RUONIA_EXCHANGE:spx-feed-cbr-ruonia-exchange}
    ruoniasv:
      exchange: ${RABBIT_FEED_RUONIASV_EXCHANGE:spx-feed-cbr-ruoniasv-exchange}
    keyrate:
      exchange: ${RABBIT_FEED_KEYRATE_EXCHANGE:spx-feed-cbr-keyrate-exchange}

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${HDB_HOST:localhost}:${HDB_PORT:5432}/${HDB_DATABASE:spimex_db}
    username: ${HDB_USER:spx_cbr_user}
    password: ${HDB_PASSWORD}
    hikari:
      maximumPoolSize: ${DB_MAX_CONNECTIONS:3}

  quartz:
    job-store-type: memory
    properties:
      org:
        quartz:
          jobStore:
            class: org.quartz.simpl.RAMJobStore
          scheduler:
            instanceId: AUTO
            isClustered: true
            useProperties: true
            instanceName: spimex-scheduler
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 1

feign:
  period-seconds: ${CBR_SERVICE_PERIOD_SECONDS:30}
  maxPeriod-seconds: ${CBR_SERVICE_MAX_PERIOD_SECONDS:35}
  maxAttempts: ${CBR_SERVICE_MAX_ATTEMPTS:10}
  url-client: ${CBR_SERVICE_URL:https://www.cbr.ru}
  httpclient:
    connection-timeout: 3000
  retryAfterException:
    maxAttempts: ${CBR_SERVICE_MAX_ATTEMPTS_EXCEPTION:3}
    delay: ${CBR_SERVICE_DELAY_EXCEPTION:180000}

schedulers:
  currency:
    enable: true
    permanent-jobs-group-name: CBR
    show-time-job-cron: ${CBR_CURRENCY_JOB_CRON:0 0 15 ? * * *}
#    show-time-job-cron: ${CBR_CURRENCY_JOB_CRON:*/15 * * * * ?}    # Just for testing, if need it.
  rates:
    enable: true
    permanent-jobs-group-name: rates
    show-time-job-cron: ${CBR_CURRENCY_RATES_JOB_CRON:0 10 12 * * ?}
  metal:
    enable: true
    permanent-jobs-group-name: metal
    show-time-job-cron: ${CBR_METAL_RATES_JOB_CRON:0 20 12 * * ?}
  ruonia:
    enable: true
    permanent-jobs-group-name: ruonia
    show-time-job-cron: ${CBR_RUONIA_JOB_CRON:0 30 12 * * ?}
  ruoniasv:
    enable: true
    permanent-jobs-group-name: ruoniasv
    show-time-job-cron: ${CBR_RUONIASV_JOB_CRON:0 40 12 * * ?}
  keyrate:
    enable: true
    permanent-jobs-group-name: keyrate
    show-time-job-cron: ${CBR_KEY_RATE_JOB_CRON:0 50 12 * * ?}

mybatis:
  configuration:
    map-underscore-to-camel-case: true

spx-feed-cbr:
  var:
    hist-cur-rates-start-date: 12/01/2010
    hist-metal-rates-start-date: 01/07/2001
    hist-ruonia-start-date: 2010-01-01
    hist-key-rate-start-date: 2010-01-01
    metal-start-day-from-today: 7
    ruonia-start-day-from-today: 7
    ruoniasv-start-day-from-today: 7
